[tool.poetry]
name = "monorepo"
version = "0.1.0"
description = "Monorepo for local development"
authors = ["frickp <peter.l.frick@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
